export const mapping_pl = {
  login: 'Zaloguj się teraz',
  login_social_media:
    'Zaloguj się za pomocą Facebooka lub innych mediów społecznościowych',
  password: 'Hasło',
  your_email: 'Twój email',
  login_description:
    'Wprowadź swój adres e-mail i hasło, aby się zalogować. Jeśli zalogowałeś się przez Facebook lub inną opcję, kliknij „Inne opcje logowania',
  create_account_with_email: 'Utwórz konto za pomocą mojego e-maila',
  login_account: 'Konto logowania',
  login_button: 'Zaloguj Się',
  provide_email: 'Musisz podać adres e-mail',
  provide_password: 'Musisz podać hasło',
  provide_firstname: 'Imię jest konieczne',
  provide_lastname: 'Nazwisko jest konieczne',
  provide_phone: 'Telefon jest konieczny',
  provide_correct_email: 'Twój adres e-mail jest nieprawidłowy',
  provide_password_min_6: 'Minimalna długość hasła powinna wynosić 6 znaków',
  provide_password_confirm: 'Potwierdź hasło jest konieczne',
  provide_password_mismatch: 'Hasło i potwierdzenie hasła nie są zgodne',
  filter: 'Filtr',
  tap_to_search: 'Wybierz, aby wyszukać...',
  search_focus_hint: 'Wyszukaj nazwę łodzi, model...',
  back: 'Wróć',
  login_header:
    'Zaloguj się na swoje konto, jeśli nie masz jeszcze konta, kliknij „Zarejestruj się teraz".',
  login_profile_header:
    'Aby uzyskać dostęp do swojego profilu, musisz się zalogować',
  login_user_yachts_header:
    'Zaloguj się na swoje konto, a następnie pokażemy Ci listę jachtów.',
  login_yacht_form_header: 'Aby dodać jacht, musisz się zalogować',
  no_result: 'Nie możemy znaleźć żadnego wyniku dla Twoich filtrów!',
  keyword_placeholder: 'Nazwa łodzi, model, typ...',

  no_internet_connection: 'Brak połączenia z internetem',
  boat_name: 'Nazwa łodzi, model lub tytuł',
  boat_price: 'Cena łodzi %sample_price%',
  marked_field: 'Sprawdź zaznaczone pola i uzupełnij je',
  boat_general_info: 'Ogólne informacje o łodzi',
  equipments_on_board: 'Sprzęt na pokładzie',
  update_boat: 'Zaktualizuj łódź',
  save_boat: 'Zapisz łódź',
  boat_save_terms:
    'Zapisując informacje o łodzi, będzie ona widoczna dla wszystkich. Upewnij się, że przeczytałeś „Kod serwisowy” na stronie internetowej PixelPlux.',
  images_count: 'Obrazy (%count%)',
  select_location: 'Wybierz lokalizację',
  technical_info: 'Specyfikacja',
  required_license: 'Czy żeglarz tej łodzi wymaga licencji?',
  boat_has_trailer: 'Czy łódź posiada również przyczepę?',
  boat_operation_status:
    'Czy statek ma wszystkie urządzenia sprawnie działające?',
  my_boats: 'Moje łodzie',
  favorite_list: 'Ulubiona lista',
  no_location: 'Nieznana lokalizacja',
  apply_filters: 'Zastosuj filtry',
  location: 'Lokalizacja',
  filter_keyword_placeholder: 'Nazwa łodzi, typ lub model',
  price_range: 'Przedział cenowy',
  price_from: 'Z',
  price_to: 'Do',
  reset_filters: 'Zresetuj wszystkie filtry',
  cancel: 'Anuluj',
  location_search_placeholder: 'Kraj, miasto, miasto ...',
  // @to do check it
  bimini: 'Daszek przeciwsłoneczny',

  option_equipment_bimini: 'Daszek przeciwsłoneczny',
  option_navigation_outboard: 'Silnik zaburtowy',
  option_equipment_bathing_ladder: 'Drabinka kąpielowa',
  // @ to do check it
  option_navigation_outboard_motor: 'Silnik przyczepny',
  // @ to do check it
  option_navigation_bow_thruster: 'Ster strumieniowy',
  option_equipment_dining_table: 'Stół obiadowy',
  option_navigation_electric_windlass: 'Elektryczna winda kotwiczna',
  // @to do check it
  option_equipment_bow_sundeck: 'Łuk łukowy',
  option_navigation_gps: 'GPS',
  option_equipment_deck_shower: 'Prysznic na pokładzie',
  option_navigation_depth_sounder: 'Sygnalizator głębokości',
  option_navigation_vhf: 'VHF',
  option_navigation_automatic_pilot: 'Pilot automatyczny',
  option_kitchen_freezer: 'Zamrażarka',
  option_energy_220v_socket: 'Gniazdo 220V',
  option_kitchen_oven: 'Piekarnik',
  option_energy_usb: 'USB',
  option_kitchen_refrigerator: 'Lodówka',
  option_kitchen_sink: 'Zlew',
  outdoor_equipment: 'Sprzęt zewnętrzny',
  navigation_equipment: 'Sprzęt nawigacyjny',
  energy: 'Energia',
  kitchen: 'Kuchnia',
  image_select_title:
    'Dotknij, aby wybrać zdjęcie. Dotknij zdjęcia, aby je edytować.',
  yes: 'Tak',
  no: 'Nie',
  price_for: 'Cena %price%',
  filters: 'Filtry',
  view_my_boats: 'Zobacz moje łodzie',
  sign_out: 'Wyloguj się',
  edit_profile: 'Edytuj swój profil',
  language: 'Język (Language):',
  lang_en: 'Język angielski (English)',
  lang_pl: 'Polski (polski)',
  lang_ru: 'Rosyjski (русский)',
  your_currency: 'Twoja waluta:',
  update_profile: 'Zaktualizuj profil',
  back_to_profile: 'Wróć z powrotem do profilu',
  confirm_password: 'Potwierdź hasło',
  phone: 'Telefon',
  last_name: 'Nazwisko',
  first_name: 'Imię',
  change_picture: 'Zmień zdjęcie',
  other_login_options: 'Inne opcje logowania',
  login_with_email: 'Zaloguj się za pomocą istniejącego e-maila',

  signup_screen_title:
    'Wprowadź wymagane informacje, aby utworzyć nowe konto, lub zaloguj się, klikając „Inne opcje logowania”',
  create_account: 'Utwórz konto',
  try_again_later: 'Spróbuj ponownie później',
  account_been_created: 'Twoje konto zostało utworzone %name%!',
  something_went_wrong: 'Coś poszło nie tak, spróbuj ponownie później',
  accept_terms: 'Najpierw zaakceptuj warunki',
  confirm: 'Potwierdź',
  accept: 'Zaakceptuj',
  terms_of_use: 'Warunki korzystania',
  and: 'I',
  privacy_policy: 'Polityka prywatności',
  connect_with_facebook: 'Połącz z Facebookiem',
  conenct_with_google: 'Połącz się z Google',
  by_continue_you_agree: 'Kontynuując, zgadzasz się również na dokayak',
  facebook_cannot_login: 'Nie możesz się zalogować przez Facebook',
  boat_type_form: 'Typ łodzi (struktura)',
  vessel_length_form: 'Długość łodzi (metry)',
  engine_hp_form: 'moc silnika',
  there_are_no_boats_fav:
    'Nie wybrałeś jeszcze żadnej łodzi. Kliknij przycisk „Serce” na dowolnej łodzi, aby zachować ją tutaj.',
  call_number: 'Zadzwoń na numer',
  text_message: 'Wiadomość tekstowa',
  copy_number: 'Skopiuj numer',
  yacht_single_num_click: 'Co zrobić z numerem?',
  boat_text_message_template:
    '„Witaj %recipient%, interesuje mnie„ %title% ”. Pozdrawiam, %sender%',
  visitor_from_dokayak: 'Gość z dokayak',

  map_selected_location: 'Wybrana lokalizacja',
  boat_type_necessary: 'Typ łodzi jest konieczny do wyboru',
  boat_name_necessary: 'Nazwa jachtu jest konieczna.',
  at_least_one_image:
    'Potrzebny jest co najmniej jeden obraz. Dodaj 5 lub więcej obrazów, aby lepiej wpłynąć na odbiorców.',
  boat_price_necessary: 'Cena jachtu jest konieczna.',
  phone_is_necessary:
    'Numer kontaktowy jest konieczny, aby ludzie mogli się z Tobą skontaktować',
  boat_license_necessary:
    'Konieczny jest typ licencji łodzi. Jeśli załoga wymaga posiadania licencji, wybierz „Tak”. W przeciwnym razie wybierz „Nie”',
  boat_trailer_necessary:
    'Jeśli masz przyczepę, wybierz „Tak”. Wiele osób chce wiedzieć, czy możesz dostarczyć przyczepę.',
  boat_operation_status_necessary:
    'Status łodzi pomaga uzyskać lepszy cel. Jeśli łódź jest gotowa do wypłynięcia bez jakiejkolwiek naprawy, wybierz „Tak”.',
  boat_having_errors:
    'Informacje o jachcie muszą zostać wypełnione, sprawdź niektóre pola zawierające błąd',
  current_and_original_currency_warning:
    'Ta waluta reklamy to (%original_currency%) i inna niż bieżąca waluta. Jeśli nie zmienisz waluty, nie zostanie zmieniona.',
  account_picture_successfully_updated:
    'Obraz Twojego konta został zaktualizowany',
  cannot_upload_picture: 'Nie możemy przesłać tego obrazu',
  account_been_updated: 'Twoje konto zostało zaktualizowane %name%!',
  currency_notice:
    'Jeśli nie znajdziesz swojej waluty / języka, wybierz najbardziej popularną walutę (Euro / USD).',
  please_select_localisation_initial:
    'Idealnie byłoby ustawić walutę i kraj na początku.',
  set_and_continue: 'Ustaw i kontynuuj',
  engine_stroke_form: 'skok silnika',
  boat_current_env_form: 'Obecne środowisko łodzi',
  sleeping_capacity_form: 'możliwość spania',
  boat_launch_option_form: 'Stan uruchomienia łodzi',
  _4_stroke_engine: '4-suwowy silnik',
  _2_stroke_engine: 'Silnik dwusuwowy',
  can_be_moved_to_ground: 'Tak, można uruchomić na wodzie',
  cannot_be_moved_to_ground: 'Nie, nie można uruchomić na wodzie',
  on_the_ground: 'Na ziemi',
  on_the_water: 'Na wodzie',
  boat_on_board_capacity_form: 'ilość  ludzi na pokładzie',
  boat_engine_info: 'Informacje o silniku łodzi',
  boat_cabin_info: 'Informacje o kabinie łodzi',
  boat_testing_info: 'Testy łodzi i uruchomienie',
  pick_photo_from: 'Wybierz zdjęcie z ...',
  take_photo_camera: 'Zrób zdjęcie (aparat)',
  gallery: 'Galeria',
  cancel: 'Anuluj',
  mine: 'Mój',
  home_screen: 'Główna',
  new_screen: 'Dodaj',
  profile_screen: 'Profil',
  favorites_screen: 'Ulubione',
  e_permission_missing:
    'Wymagane pozwolenie na robienie zdjęć lub wybór z galerii. Być może będziesz musiał przejść do „ustawień” telefonu i wyrazić zgodę na dokayak',
  boat_construction_year_form: 'Rok budowy',
  vessel_width_form: 'Szerokość łodzi (metry)',
  'meter_match_00.00': 'Tylko pływak, z wyjątkiem 10.5',
  user_yachts_empty:
    'Nie masz żadnych łodzi. Dotknij Dodaj ikonę poniżej, aby dodać swoją'
};
